version: "3"
services:
  node-app:
    build:
      context: ./server   # Path to your Node.js backend directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_database_name
  redis:
    image: redis:latest
  react-app:
    build:
      context: ./client   # Path to your React frontend directory
      dockerfile: Dockerfile
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf   # Mount your Nginx configuration
